name: cfmem
 
# on:
#   workflow_dispatch:
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
 
jobs:
  cfmem:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install BeautifulSoup4
    - name: get results
      run: |
        python cfmem.py
        # git config --global user.email "${{ secrets.GT_EMAIL }}"
        # git config --global user.name "${{ secrets.GT_ACTOR }}"
        # git add .
        # git commit -m "update"
        # git push
    - name: save results
      uses: ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.GH_TOKEN }}
        # repository: ${{ secrets.GH_PATH }}
        directory: .
        branch: config
        force: true
