name: cfmem
 
on:
  push:
    branches: [ master ]
 
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
 
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install requests
        pip3 install BeautifulSoup
    - name: save results
      run: |
        python cfmem.py
        git config --global user.email "${{ secrets.GT_EMAIL }}"
        git config --global user.name "${{ secrets.GT_ACTOR }}"
        git add .
        git commit -m "update"
        git push
