name: v2rayse
 
# on:
#   workflow_dispatch:
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/1 * * *'
 
jobs:
  v2rayse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install selenium-wire
        pip install pyperclip
        pip install setuptools
        pip install webdriver-manager
        pip install blinker==1.7.0
        pip install ruamel.yaml

    # 安装Chrome的开源版本（Chromium）
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser xclip xvfb
    # 启动X虚拟服务器（指定显示端口:99）
    # 导出显示变量，让Chrome和xclip使用虚拟显示器
    - name: get results
      run: |
        Xvfb :99 -screen 0 1280x720x16 &
        export DISPLAY=:99
        python v2rayse.py
        xvfb-run -a python v2rayse.py
        git config --global user.email "${{ secrets.GT_EMAIL }}"
        git config --global user.name "${{ secrets.GT_ACTOR }}"
        git add .
        git commit -m "update"
        # git push
    - name: save results
      uses: ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.GH_TOKEN }}
        # repository: ${{ secrets.GH_PATH }}
        directory: .
        branch: config
        force: true
